// src/App.tsx
import { Outlet } from 'react-router-dom'
import Navbar from './components/Navbar'

const App = () => {
  return (
    <div>
      <div className="drawer">
        <input id="my-drawer-3" type="checkbox" className="drawer-toggle" />
        <div className="drawer-content flex flex-col">
          <div className="navbar w-full bg-base-300">
            <div className="flex-none lg:hidden">
              <label htmlFor="my-drawer-3" className="btn btn-ghost btn-square">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  className="inline-block h-6 w-6 stroke-current"
                >
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16" />
                </svg>
              </label>
            </div>
            <div className="mx-2 flex-1 px-2">Calculators</div>
            <div className="hidden flex-none lg:block">
              <ul className="menu menu-horizontal">
                <Navbar />
              </ul>
            </div>
          </div>
          <Outlet />
        </div>
        <div className="drawer-side">
          <label htmlFor="my-drawer-3" className="drawer-overlay" />
          <ul className="menu w-80 overflow-y-auto bg-base-100 p-4">
            <Navbar />
          </ul>
        </div>
      </div>
      <footer className="footer footer-center fixed bottom-0 bg-base-300 p-4 text-base-content">
        <div className="flex items-center justify-between">
          <div className="mt-0 flex space-x-6">
            <p>
              Made by{' '}
              <a href="https://github.com/Kalmarv" className="link link-hover">
                Kalmarv
              </a>{' '}
              with ❤
            </p>
          </div>
        </div>
      </footer>
    </div>
  )
}

export default App

// src/App.svelte
<script lang="ts">
  import Home from './components/Home.svelte'
  import Current from './components/Current.svelte'
  import Navbar from './components/Navbar.svelte'
  import Random from './components/Random.svelte'
  import Convert from './components/Convert.svelte'

  let page = document.location.hash
  window.onpopstate = (event: PopStateEvent) => {
    page = document.location.hash
  }
</script>

<div class="drawer">
  <input id="my-drawer-3" type="checkbox" class="drawer-toggle" />
  <div class="drawer-content flex flex-col">
    <!-- Navbar -->
    <div class="w-full navbar bg-base-300">
      <div class="flex-none lg:hidden">
        <label for="my-drawer-3" class="btn btn-square btn-ghost">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            class="inline-block w-6 h-6 stroke-current"
            ><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" /></svg
          >
        </label>
      </div>
      <div class="flex-1 px-2 mx-2">Calculators</div>
      <div class="flex-none hidden lg:block">
        <ul class="menu menu-horizontal">
          <Navbar />
        </ul>
      </div>
    </div>
    {#if page === '#home'}
      <Home />
    {:else if page === '#current'}
      <Current />
    {:else if page === '#convert'}
      <Convert />
    {:else if page === '#random'}
      <Random />
    {:else}
      <Home />
    {/if}
  </div>
  <div class="drawer-side">
    <label for="my-drawer-3" class="drawer-overlay" />
    <ul class="menu p-4 overflow-y-auto w-80 bg-base-100">
      <Navbar />
    </ul>
  </div>
</div>
<footer class="fixed bottom-0 footer footer-center p-4 bg-base-300 text-base-content">
  <div class="flex items-center justify-between">
    <div class="flex space-x-6 mt-0">
      <p>
        Made by
        <a href="https://github.com/Kalmarv" class="link link-hover">Kalmarv</a> with ❤
      </p>
    </div>
  </div>
</footer>
